name: cleenzo
description: Cleenzo - Home Care In Minutes
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.5.0

  # Network
  http: ^1.2.0

  # Navigation
  go_router: ^13.0.0

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # UI
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0
  shimmer: ^3.0.0

  # Storage
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2

  # Utils
  intl: ^0.19.0
  url_launcher: ^6.3.0
  pin_code_fields: ^8.0.1

  cupertino_icons: ^1.0.6

  # Maps & Location
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  permission_handler: ^11.3.1

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#06B6D4"
  adaptive_icon_foreground: "assets/logo.png"
  web:
    generate: false
  windows:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/services/after.png
    - assets/services/fan-cleaning.png
    - assets/services/balcony-cleaning.png
    - assets/services/fridge-cleaning.png
    - assets/services/bathroom-cleaning.png
    - assets/services/full-home-cleaning.png
    - assets/services/wardrobe.png
    - assets/services/Utensils-cleaning.png
    - assets/services/cabinet.png
    - assets/services/pre.png
    - assets/services/dusting-wiping.png
    - assets/services/kitchen-cleaning.png
    - assets/services/sweeping-mopping.png